# Generated by Django 5.2.4 on 2025-07-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance',
            field=models.IntegerField(default=0, verbose_name='موجودی کاربر (تومان)'),
        ),
    ]
