# Generated by Django 5.2.7 on 2025-10-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_remove_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه')], default=1, max_length=10, verbose_name='نوع'),
            preserve_default=False,
        ),
    ]
